/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.JFrame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Divya
 */
public class NewJFrameBookLoan extends javax.swing.JFrame {
    Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
Statement stmt = null;
DefaultTableModel model;


    /**
     * Creates new form NewJFrame3
     */
    public NewJFrameBookLoan() {
        initComponents();
        initComponents();
     try {
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "divya");
         // Create a SQL statement object and execute the query.
	   stmt = conn.createStatement();
		
			// Set the current database, if not already set in the getConnection
			// Execute a SQL statement
			stmt.execute("use library;");
                        Update_table();
     } catch (SQLException ex) {
         Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    
    public void Update_table(){
     try {
         String sql = "SELECT * FROM borrower;";
         pst = conn.prepareStatement(sql);
         rs = pst.executeQuery(sql);
         //BorrowerTable.setModel(DbUtils.resultSetToTableModel(rs));
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,ex);
        
         //Logger.getLogger(NewJFrame2.class.getName()).log(Level.SEVERE, null, ex);
     }
    } 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      @Override
    public void setDefaultCloseOperation(int operation) {
        //super.setDefaultCloseOperation(operation); 
        super.setDefaultCloseOperation(NewJFrame2.DISPOSE_ON_CLOSE);//To change body of generated methods, choose Tools | Templates.
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BookIDOutLabel = new javax.swing.JLabel();
        BranchIDOutLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BookIdInLabel = new javax.swing.JLabel();
        BorrowerNameInLabel = new javax.swing.JLabel();
        CardNumberInLabel = new javax.swing.JLabel();
        bookidout = new javax.swing.JTextField();
        BranchIDOutTextField = new javax.swing.JTextField();
        CardNumberOutTextField = new javax.swing.JTextField();
        BookIdInTextField = new javax.swing.JTextField();
        BorrowerNameInTextField = new javax.swing.JTextField();
        CardNoInTextField = new javax.swing.JTextField();
        CheckOutButton = new javax.swing.JButton();
        CheckInButton = new javax.swing.JButton();
        ClearOutButton = new javax.swing.JButton();
        ClearInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BOOK CHECK OUT");

        jLabel2.setText("BOOK CHECK IN");

        BookIDOutLabel.setText("Book ID");

        BranchIDOutLabel.setText("Branch ID");

        jLabel5.setText("Card Number");

        BookIdInLabel.setText("Book ID");

        BorrowerNameInLabel.setText("Borrower Name");

        CardNumberInLabel.setText("Card Number");

        BranchIDOutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchIDOutTextFieldActionPerformed(evt);
            }
        });

        CardNumberOutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberOutTextFieldActionPerformed(evt);
            }
        });

        CardNoInTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNoInTextFieldActionPerformed(evt);
            }
        });

        CheckOutButton.setText("Check Out");

        CheckInButton.setText("Check In");

        ClearOutButton.setText("Clear");
        ClearOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearOutButtonActionPerformed(evt);
            }
        });

        ClearInButton.setText("Clear");
        ClearInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(CheckOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearOutButton)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BranchIDOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BookIDOutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookidout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(BranchIDOutTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CardNumberOutTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(CheckInButton))
                                    .addComponent(CardNumberInLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ClearInButton)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(CardNoInTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BookIdInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BorrowerNameInLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BookIdInTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(BorrowerNameInTextField))))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BookIDOutLabel)
                                    .addComponent(bookidout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BranchIDOutLabel)
                                    .addComponent(BranchIDOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BookIdInLabel)
                                    .addComponent(BookIdInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BorrowerNameInLabel)
                                    .addComponent(BorrowerNameInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(CardNumberOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CardNumberInLabel)
                                    .addComponent(CardNoInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckOutButton)
                            .addComponent(ClearOutButton))
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckInButton)
                            .addComponent(ClearInButton))
                        .addGap(237, 237, 237))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BranchIDOutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchIDOutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchIDOutTextFieldActionPerformed

    private void CardNumberOutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberOutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumberOutTextFieldActionPerformed

    private void CardNoInTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNoInTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNoInTextFieldActionPerformed

    private void ClearOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearOutButtonActionPerformed
        String test = bookidout.getText();
       //bookidout.setVisible(false);
       BranchIDOutTextField.setText("");
       CardNumberOutTextField.setText("");
       System.out.println("valur" + test);
       
    }//GEN-LAST:event_ClearOutButtonActionPerformed

    private void ClearInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearInButtonActionPerformed
       BookIdInTextField.setText("");
       BorrowerNameInTextField.setText("");
       CardNoInTextField.setText("");
    }//GEN-LAST:event_ClearInButtonActionPerformed

    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameBookLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameBookLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameBookLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameBookLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameBookLoan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookIDOutLabel;
    private javax.swing.JLabel BookIdInLabel;
    private javax.swing.JTextField BookIdInTextField;
    private javax.swing.JLabel BorrowerNameInLabel;
    private javax.swing.JTextField BorrowerNameInTextField;
    private javax.swing.JLabel BranchIDOutLabel;
    private javax.swing.JTextField BranchIDOutTextField;
    private javax.swing.JTextField CardNoInTextField;
    private javax.swing.JLabel CardNumberInLabel;
    private javax.swing.JTextField CardNumberOutTextField;
    private javax.swing.JButton CheckInButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton ClearInButton;
    private javax.swing.JButton ClearOutButton;
    private javax.swing.JTextField bookidout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
